kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    pull: default
    image: rancher/dapper:v0.5.4
    commands:
      - dapper ci
    privileged: true
    volumes:
    - name: docker
      path: /var/run/docker.sock
    when:
      event:
      - tag
      - pull_request

  - name: github_binary_release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
      - "dist/artifacts/*"
    when:
      instance:
      - drone-publish.rancher.io
      ref:
      - refs/head/master
      - refs/tags/*
      event:
      - tag

  - name: stage-binaries
    image: rancher/dapper:v0.5.4
    commands:
      - "cp -r ./bin/* ./package/"
    when:
      event:
        - tag

  - name: docker-publish
    image: plugins/docker
    settings:
      purge: false
      context: package/
      dockerfile: package/Dockerfile
      password:
        from_secret: docker_password
      repo: rancher/machine
      tag: "${DRONE_TAG}-amd64"
      username:
        from_secret: docker_username
    when:
      event:
        - tag

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

---

kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    pull: default
    image: rancher/dapper:v0.5.4
    commands:
      - dapper ci
    privileged: true
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - tag
        - pull_request

  - name: github_binary_release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
      - "dist/artifacts/*"
    when:
      instance:
      - drone-publish.rancher.io
      ref:
      - refs/head/master
      - refs/tags/*
      event:
      - tag

  - name: stage-binaries
    image: rancher/dapper:v0.5.4
    commands:
      - "cp -r ./bin/* ./package/"
    when:
      event:
        - tag

  - name: docker-publish
    image: plugins/docker
    settings:
      purge: false
      context: package/
      dockerfile: package/Dockerfile
      password:
        from_secret: docker_password
      repo: rancher/machine
      tag: "${DRONE_TAG}-arm64"
      username:
        from_secret: docker_username
    when:
      event:
        - tag

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

---

kind: pipeline
name: s390x

platform:
  os: linux
  arch: amd64

node:
  arch: s390x

steps:
  - name: docker-publish
    image: rancher/drone-images:docker-s390x
    settings:
      purge: false
      context: package/
      dockerfile: package/Dockerfile
      password:
        from_secret: docker_password
      repo: rancher/machine
      tag: "${DRONE_TAG}-s390x"
      username:
        from_secret: docker_username
    volumes:
    - name: docker
      path: /var/run/docker.sock

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

---

kind: pipeline
name: manifest

steps:
  - name: push-manifest
    image: plugins/manifest:1.0.2
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/s390x
      target: "rancher/machine:${DRONE_TAG}"
      template: "rancher/machine:${DRONE_TAG}-ARCH"
    when:
      event:
      - tag

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

trigger:
  event:
    - tag

depends_on:
  - amd64
  - arm64
  - s390x
